name: CI
on:
  push:
    branches: [master]
jobs:
  build-debian:
    name: Build proxy package
    runs-on: ubuntu-22.04
    env:
      VERSION: 0.0.0
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'
      - name: Build package
        run: make build-deb VERSION=${{ env.VERSION }}
      - name: Check artifact
        run: mv .build/nx-proxy-${{ env.VERSION }}.deb .build/nx-proxy-${{ env.VERSION }}-amd64.deb
